// Date: 12/07/2014 11:42:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package evilcraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.obj.WavefrontObject;

import org.lwjgl.opengl.GL11;

import evilcraft.Reference;

/**
 * Model for the Box of Eternal Closure
 * @author rubensworks
 *
 */
public class BoxOfEternalClosureModel extends ModelBase {
	
	private static WavefrontObject mainModel = new WavefrontObject(
			new ResourceLocation(Reference.MOD_ID, Reference.MODEL_PATH + "box.obj"));
	private static WavefrontObject coverModel = new WavefrontObject(
			new ResourceLocation(Reference.MOD_ID, Reference.MODEL_PATH + "boxCover.obj"));
	
	private float rotationX = -0.29F;
	private float rotationY = 0.19F;
	private float rotationZ = 0F;
	
	private float coverAngle = 0F;

	/**
	 * Make a new instance.
	 */
	public BoxOfEternalClosureModel() {
		
	}
	
	/**
	 * Set the angle of the lid.
	 * @param coverAngle The lid angle.
	 */
	public void setCoverAngle(float coverAngle) {
		this.coverAngle = coverAngle;
	}
	
	/**
     * This method renders out all parts of the box model.
     */
    public void renderAll() {
    	GL11.glRotatef(90F, 0F, 1F, 0F);
    	GL11.glRotatef(180F, 1F, 0F, 0F);
    	GL11.glTranslatef(-0.5F, -0.76F, -0.5F);
    	GL11.glScalef(1F, 1F, 0.95F);
    	mainModel.renderAll();
    	
    	GL11.glPushMatrix();
    	GL11.glTranslatef(rotationX, rotationY, rotationZ);
    	GL11.glRotatef(coverAngle, 0F, 0F, 1F);
    	GL11.glTranslatef(-rotationX, -rotationY, -rotationZ);
    	coverModel.renderAll();
    	GL11.glPopMatrix();
    }

}
