// Date: 24/01/2014 21:58:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package org.cyclops.evilcraft.client.render.entity;

import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import net.minecraft.client.renderer.entity.model.BipedModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import org.cyclops.evilcraft.entity.monster.EntityWerewolf;

/**
 * @author Davivs69
 */
public class ModelWerewolf extends BipedModel<EntityWerewolf> {
    //fields
    ModelRenderer bipedEar1;
    ModelRenderer bipedEar2;
    ModelRenderer Upper_Jaw;
    ModelRenderer Lower_Jaw;

    /**
     * Make a new instance.
     */
    public ModelWerewolf() {
        super(1.0F);
        this.textureWidth = 64;
        this.textureHeight = 135;
        bipedHead = new ModelRenderer(this, 24, 0);
        bipedHead.addBox(-5F, -10F, -5F, 10, 10, 10);
        bipedHead.setRotationPoint(0F, -13F, 0F);
        bipedHead.setTextureSize(64, 135);
        bipedHead.mirror = true;
        setRotation(bipedHead, 0F, 0F, 0F);
        bipedEar1 = new ModelRenderer(this, 18, 0);
        bipedEar1.addBox(-4F, -14F, 2F, 2, 4, 1);
        bipedEar1.setRotationPoint(0F, -13F, 0F);
        bipedEar1.setTextureSize(64, 135);
        bipedEar1.mirror = true;
        setRotation(bipedEar1, 0F, 0F, 0F);
        bipedEar2 = new ModelRenderer(this, 12, 0);
        bipedEar2.addBox(2F, -14F, 2F, 2, 4, 1);
        bipedEar2.setRotationPoint(0F, -13F, 0F);
        bipedEar2.setTextureSize(64, 135);
        bipedEar2.mirror = true;
        setRotation(bipedEar2, 0F, 0F, 0F);
        Upper_Jaw = new ModelRenderer(this, 32, 122);
        Upper_Jaw.addBox(-3F, -7F, -11F, 6, 3, 10);
        Upper_Jaw.setRotationPoint(0F, -13F, 0F);
        Upper_Jaw.setTextureSize(64, 135);
        Upper_Jaw.mirror = true;
        setRotation(Upper_Jaw, 0F, 0F, 0F);
        Lower_Jaw = new ModelRenderer(this, 0, 122);
        Lower_Jaw.addBox(-3F, -4F, -10F, 6, 2, 10);
        Lower_Jaw.setRotationPoint(0F, -13F, 0F);
        Lower_Jaw.setTextureSize(64, 135);
        Lower_Jaw.mirror = true;
        setRotation(Lower_Jaw, 0.1745329F, 0F, 0F);
        bipedBody = new ModelRenderer(this, 12, 20);
        bipedBody.addBox(-7F, 0F, -6F, 14, 19, 12);
        bipedBody.setRotationPoint(0F, -13F, 0F);
        bipedBody.setTextureSize(64, 135);
        bipedBody.mirror = true;
        setRotation(bipedBody, 0F, 0F, 0F);
        bipedRightArm = new ModelRenderer(this, 22, 51);
        bipedRightArm.addBox(-4F, -2F, -16F, 4, 4, 17);
        bipedRightArm.setRotationPoint(-7F, -8F, 0F);
        bipedRightArm.setTextureSize(64, 135);
        bipedRightArm.mirror = true;
        setRotation(bipedRightArm, 0.1047198F, 0F, 0F);
        bipedLeftArm = new ModelRenderer(this, 0, 72);
        bipedLeftArm.addBox(0F, -2F, -16F, 4, 4, 17);
        bipedLeftArm.setRotationPoint(7F, -8F, 0F);
        bipedLeftArm.setTextureSize(64, 135);
        bipedLeftArm.mirror = true;
        setRotation(bipedLeftArm, 0.1047198F, 0F, 0F);
        bipedRightLeg = new ModelRenderer(this, 44, 93);
        bipedRightLeg.addBox(-2.5F, 0F, -2.5F, 5, 18, 5);
        bipedRightLeg.setRotationPoint(-3F, 6F, 0F);
        bipedRightLeg.setTextureSize(64, 135);
        bipedRightLeg.mirror = true;
        setRotation(bipedRightLeg, 0F, 0F, 0F);
        bipedLeftLeg = new ModelRenderer(this, 24, 93);
        bipedLeftLeg.addBox(-2.5F, 0F, -2.5F, 5, 18, 5);
        bipedLeftLeg.setRotationPoint(3F, 6F, 0F);
        bipedLeftLeg.setTextureSize(64, 135);
        bipedLeftLeg.mirror = true;
        setRotation(bipedLeftLeg, 0F, 0F, 0F);
    }

    @Override
    public void render(MatrixStack matrixStackIn, IVertexBuilder bufferIn, int packedLightIn, int packedOverlayIn, float red, float green, float blue, float alpha) {
        super.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedHead.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedEar1.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedEar2.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        Upper_Jaw.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        Lower_Jaw.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedBody.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedRightArm.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedLeftArm.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedRightLeg.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
        bipedLeftLeg.render(matrixStackIn, bufferIn, packedLightIn, packedOverlayIn, red, green, blue, alpha);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(EntityWerewolf entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        super.setRotationAngles(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        bipedHead.setRotationPoint(0F, -13F, 0F);
        bipedRightArm.setRotationPoint(-7F, -8F, 0F);
        bipedLeftArm.setRotationPoint(7F, -8F, 0F);
        bipedRightLeg.setRotationPoint(-3F, 6F, 0F);
        bipedLeftLeg.setRotationPoint(3F, 6F, 0F);

        this.bipedEar1.rotateAngleY = this.bipedHead.rotateAngleY;
        this.bipedEar1.rotateAngleX = this.bipedHead.rotateAngleX;
        this.bipedEar2.rotateAngleY = this.bipedHead.rotateAngleY;
        this.bipedEar2.rotateAngleX = this.bipedHead.rotateAngleX;

        float barkRotation = entityIn.getBarkProgressScaled(0.1745329F);
        setRotation(Upper_Jaw, this.bipedHead.rotateAngleX + 0F, this.bipedHead.rotateAngleY + 0F, 0F);
        setRotation(Lower_Jaw, this.bipedHead.rotateAngleX + barkRotation, this.bipedHead.rotateAngleY + 0F, 0F);
    }

}
