# Project
mod_version=1.2.84
group=org.cyclops.evilcraft
java_version=25

# Common
minecraft_version=26.1.1
mod_name=EvilCraft
mod_author=rubensworks (aka kroeser)
mod_id=evilcraft
license=MIT
github_url=https://github.com/CyclopsMC/EvilCraft
issue_tracker_url=https://github.com/CyclopsMC/EvilCraft/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/evilcraft
description=An evil mod for Minecraft.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=74610
modrinth_project_id=3ANq2btA

# NeoForge
neoforge_version=26.1.1.1-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/evilcraft.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
cyclopscore_version=1.25.5-974
evilcraftcompat_version=1.1.0-126
