modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CyclopsMC/EvilCraft/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/evilcraft"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="evilcraft"
version="${file.jarVersion}"
displayName="EvilCraft"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/evilcraft.json"
description='''
An evil mod for Minecraft.
'''
[[dependencies.evilcraft]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.17.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraft]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,]"
    ordering="NONE"
    side="BOTH"
