modLoader="javafml"
loaderVersion="[31.2,)"
issueTrackerURL="https://github.com/CyclopsMC/EvilCraft/issues"
[[mods]]
modId="evilcraft"
version="${file.jarVersion}"
displayName="EvilCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/evilcraft"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
description='''
An evil mod for Minecraft.
'''
[[dependencies.evilcraft]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.8.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraft]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
