modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/EvilCraft/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/evilcraft"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="evilcraft"
version="${file.jarVersion}"
displayName="EvilCraft"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/evilcraft.json"
description='''
An evil mod for Minecraft.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.evilcraft]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraft]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evilcraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,]"
    ordering="NONE"
    side="BOTH"
