// Date: 24/01/2014 21:58:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package evilcraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * @author Davivs69
 */
public class WerewolfModel extends ModelBase {
    //fields
    ModelRenderer Caput;
    ModelRenderer Upper_Jaw;
    ModelRenderer Lower_Jaw;
    ModelRenderer Thorax;
    ModelRenderer Left_Arm;
    ModelRenderer Right_Arm;
    ModelRenderer Left_Leg;
    ModelRenderer Right_Leg;
    ModelRenderer Left_Ear;
    ModelRenderer Right_Ear;

    public WerewolfModel() {
        textureWidth = 64;
        textureHeight = 135;

        Caput = new ModelRenderer(this, 24, 0);
        Caput.addBox(0F, 0F, 0F, 10, 10, 10);
        Caput.setRotationPoint(-5F, -23F, -6F);
        Caput.setTextureSize(64, 135);
        Caput.mirror = true;
        setRotation(Caput, 0F, 0F, 0F);
        Upper_Jaw = new ModelRenderer(this, 32, 122);
        Upper_Jaw.addBox(0F, 0F, 0F, 6, 3, 10);
        Upper_Jaw.setRotationPoint(-3F, -19F, -12F);
        Upper_Jaw.setTextureSize(64, 135);
        Upper_Jaw.mirror = true;
        setRotation(Upper_Jaw, 0F, 0F, 0F);
        Lower_Jaw = new ModelRenderer(this, 0, 122);
        Lower_Jaw.addBox(0F, 0F, 0F, 6, 2, 10);
        Lower_Jaw.setRotationPoint(-3F, -15F, -11F);
        Lower_Jaw.setTextureSize(64, 135);
        Lower_Jaw.mirror = true;
        setRotation(Lower_Jaw, 0.1745329F, 0F, 0F);
        Thorax = new ModelRenderer(this, 12, 20);
        Thorax.addBox(0F, 0F, 0F, 14, 19, 12);
        Thorax.setRotationPoint(-7F, -13F, -7F);
        Thorax.setTextureSize(64, 135);
        Thorax.mirror = true;
        setRotation(Thorax, 0F, 0F, 0F);
        Left_Arm = new ModelRenderer(this, 0, 72);
        Left_Arm.addBox(0F, 0F, 0F, 4, 4, 17);
        Left_Arm.setRotationPoint(7F, -10F, -17F);
        Left_Arm.setTextureSize(64, 135);
        Left_Arm.mirror = true;
        setRotation(Left_Arm, 0.1047198F, 0F, 0F);
        Right_Arm = new ModelRenderer(this, 22, 51);
        Right_Arm.addBox(0F, 0F, 0F, 4, 4, 17);
        Right_Arm.setRotationPoint(-11F, -10F, -17F);
        Right_Arm.setTextureSize(64, 135);
        Right_Arm.mirror = true;
        setRotation(Right_Arm, 0.1047198F, 0F, 0F);
        Left_Leg = new ModelRenderer(this, 24, 93);
        Left_Leg.addBox(0F, 0F, 0F, 5, 24, 5);
        Left_Leg.setRotationPoint(1F, 0F, -3F);
        Left_Leg.setTextureSize(64, 135);
        Left_Leg.mirror = true;
        setRotation(Left_Leg, 0F, 0F, 0F);
        Right_Leg = new ModelRenderer(this, 44, 93);
        Right_Leg.addBox(0F, 0F, 0F, 5, 24, 5);
        Right_Leg.setRotationPoint(-6F, 0F, -3F);
        Right_Leg.setTextureSize(64, 135);
        Right_Leg.mirror = true;
        setRotation(Right_Leg, 0F, 0F, 0F);
        Left_Ear = new ModelRenderer(this, 12, 0);
        Left_Ear.addBox(0F, 0F, 0F, 2, 4, 1);
        Left_Ear.setRotationPoint(3F, -27F, 0F);
        Left_Ear.setTextureSize(64, 135);
        Left_Ear.mirror = true;
        setRotation(Left_Ear, 0F, 0F, 0F);
        Right_Ear = new ModelRenderer(this, 18, 0);
        Right_Ear.addBox(0F, 0F, 0F, 2, 4, 1);
        Right_Ear.setRotationPoint(-5F, -27F, 0F);
        Right_Ear.setTextureSize(64, 135);
        Right_Ear.mirror = true;
        setRotation(Right_Ear, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Caput.render(f5);
        Upper_Jaw.render(f5);
        Lower_Jaw.render(f5);
        Thorax.render(f5);
        Left_Arm.render(f5);
        Right_Arm.render(f5);
        Left_Leg.render(f5);
        Right_Leg.render(f5);
        Left_Ear.render(f5);
        Right_Ear.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
