// Date: 1/01/2014 20:13:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package evilcraft.client.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * @author Davivs69
 */
public class BroomModel extends ModelBase {
	// This offset places the player on the correct mounting point on the broom
	private static final float Z_OFFSET = 5.0f;
	
	// fields
	ModelRenderer Steel;
	ModelRenderer Gem;
	ModelRenderer Borstel;

	/**
	 * Make a new instance.
	 */
	public BroomModel() {
		textureWidth = 64;
		textureHeight = 32;

		Steel = new ModelRenderer(this, 20 , 0);
		Steel.addBox(0F, 0F, Z_OFFSET, 1, 1, 17);
		Steel.setRotationPoint(-0.5F, 0F, -17F);
		Steel.setTextureSize(64, 32);
		Steel.mirror = true;
		setRotation(Steel, 0F, 0F, 0F);
		Gem = new ModelRenderer(this, 12, 0);
		Gem.addBox(0F, 0F, Z_OFFSET, 3, 3, 1);
		Gem.setRotationPoint(0F, -1.6F, -18F);
		Gem.setTextureSize(64, 32);
		Gem.mirror = true;
		setRotation(Gem, 0F, 0F, 0.7853982F);
		Borstel = new ModelRenderer(this, 0, 4);
		Borstel.addBox(0F, 0F, Z_OFFSET, 3, 3, 7);
		Borstel.setRotationPoint(-1.5F, -1F, 0F);
		Borstel.setTextureSize(64, 32);
		Borstel.mirror = true;
		setRotation(Borstel, 0F, 0F, 0F);
	}

	@Override
	public void render(Entity entity, float moveTime, float moveSpeed, float ticksExisted, float lookYaw, float lookPitch, float scale) {
		Steel.render(scale);
		Gem.render(scale);
		Borstel.render(scale);
	}

	private void setRotation(ModelRenderer model, double x, double y, double z) {
		model.rotateAngleX = (float)x;
		model.rotateAngleY = (float)y;
		model.rotateAngleZ = (float)z;
	}

}
